export const COLOR_OPTIONS = [
  { label: "Qara", value: "Qara" },
  { label: "Ağ", value: "Ağ" },
  { label: "Göy", value: "Göy" },
  { label: "Qırmızı", value: "Qırmızı" },
  { label: "Yaşıl", value: "Yaşıl" },
  { label: "Sarı", value: "Sarı" },
  { label: "Narıncı", value: "Narıncı" },
  { label: "Bənövşəyi", value: "Bənövşəyi" },
  { label: "Çəhrayı", value: "Çəhrayı" },
  { label: "Boz", value: "Boz" },
  { label: "Tünd Göy", value: "Tünd Göy" },
  { label: "Bej", value: "Bej" },
  { label: "Qəhvəyi", value: "Qəhvəyi" },
  { label: "Ekru", value: "Ekru" },
  { label: "Qızılı", value: "Qızılı" },
  { label: "Gümüşü", value: "Gümüşü" },
  { label: "Antrasit", value: "Antrasit" },
  { label: "Bordo", value: "Bordo" },
  { label: "Xaki", value: "Xaki" },
  { label: "Mavi", value: "Mavi" },
  { label: "Turkuaz", value: "Turkuaz" },
  { label: "Lila", value: "Lila" },
  { label: "Hardal", value: "Hardal" },
  { label: "Taba", value: "Taba" },
  { label: "Fuşya", value: "Fuşya" },
  { label: "Mint", value: "Mint" },
  { label: "Mərcan", value: "Mərcan" },
  { label: "Rəngsiz / Şəffaf", value: "Rəngsiz" },
  { label: "Çoxrəngli", value: "Çoxrəngli" },
];
